### ISSUE TITLE
Feature: User can view steam games by searching a term

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view steam games by searching a term using the search bar. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click on the search bar and type in the name of a game they are looking for. When they press Search, a list of steam games with the same name will appear.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue1](https://user-images.githubusercontent.com/106547566/192327631-90b980cd-9857-4ba4-b6b4-0fdb04014a70.PNG)
![issue1mobile](https://user-images.githubusercontent.com/106547566/192327766-c5bfea2a-abbb-49b4-b42e-404d5c56ba1c.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div[data-view="games"]` to the HTML.
- [x] Add html to set up the page (nav bar icons, links, and form for the search bar, text for the title of the page)
- [x] Add css to make the page look like the wireframe. Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Listen for `'input'` events on the search bar.
   - [x] Use the input to search through the API's data and find games with the name property that match the search.  
   - [x] Put the name, logo, and app id into an object for each of the games that show up from the search.
   - [x] Use the app id to get the description, release date, genre and add those to the data object.
   - [x] Prepend each game to the entries in the data model.
- **Clean Up**
  - [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
  - [x] Test all functionality again in a private browsing session.
  - [x] Fix all errors.
