### ISSUE TITLE
Feature: User can view featured steam games

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Currently featured games will appear on the games page before using any search features.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the page loads, the user will be shown a list of currently featured games on steam. If they click on the games link, featured games will appear again, no matter which page they were on before.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![issue2mobile](https://user-images.githubusercontent.com/106547566/192658966-a7535924-cbdc-400a-8b16-9b072e987a70.PNG)
![issue2desktop](https://user-images.githubusercontent.com/106547566/192658967-3df984b2-dd79-41d9-be10-88e989494c34.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the css for the new layout
- [x] Get the data for featured steam games
- [x] Create the elements with the dom.
- [x] Hide featured games when searching for new games.
- [x] Show featured games again when clicking on the games link in the nav bar.
- **Clean Up**
-  [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
-  [x] Test all functionality again in a private browsing session.
-  [x] Fix all errors.
