### ISSUE TITLE
Feature: User can save games and view their list

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save any game to their "MyCodex".

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the heart icon on a game entry. The heart will be colored in and the game will be saved to "MyCodex". User can view MyCodex by clicking on the link in the nav bar.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue3desktop](https://user-images.githubusercontent.com/106547566/192605868-7df3e1a4-62f8-46be-a722-15bda7ec9edf.PNG)
![issue3desktop2](https://user-images.githubusercontent.com/106547566/192606220-b9139a30-dfdb-425f-b93c-09de31dbbdb5.PNG)
![issue3mobile](https://user-images.githubusercontent.com/106547566/192606212-be19e0ed-3102-4cce-970d-bfb1d0bf77c2.PNG)
![issue3mobile2](https://user-images.githubusercontent.com/106547566/192606217-f979a10b-14b1-4f20-87c0-92306bd7b686.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Give heart icons an id or class matching app id for game it corresponds to.
- [x] Put a click event on the heart icon so that it gets filled in when clicked and unfilled when clicked again.
- [x] Save game title and image of the game that has a heart and put it into local storage.
- [x] Set up the html and css for the MyCodex page.
- [x] Generate the MyCodex page using the DOM and local storage.
- [x] Have saved games heart icons always appear filled in, even in the games page.
- **Clean Up**
  - [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
  - [x] Test all functionality again in a private browsing session.
  - [x] Fix all errors.
