### ISSUE TITLE
Feature: User can view site info by clicking on the question icon

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view site info and helpful tips of use.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on the question mark icon, a modal will pop up with site info and helpful tips of use. They can press the x to close the modal.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue4mobile](https://user-images.githubusercontent.com/106547566/192884254-13d388f0-a88e-4e73-b262-8e16fa10cec7.PNG)
![issue4desktop](https://user-images.githubusercontent.com/106547566/192884255-fe5fee1f-1779-47a6-808e-21e98be4acc4.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create html and css for modal design.
- [x] Add a click event for the question mark icon in the nav bar.
- [x] Show modal when icon is clicked.
- [x] Close modal when x icon in modal is clicked.
- **Clean Up**
  - [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
  - [x] Test all functionality again in a private browsing session.
  - [x] Fix all errors.
