### ISSUE TITLE
Feature: User can add and edit info to a saved game

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view, add, and edit notes for each of their saved games.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Click on a game tile in their codex to view notes. Click on the edit icon in order to add to and edit the notes.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue5desktop](https://user-images.githubusercontent.com/106547566/193081545-cdbe0f7f-f5f2-4dfb-b643-4978dcffa507.PNG)
![issue5mobile](https://user-images.githubusercontent.com/106547566/193081549-a0ab2fb4-86cc-430a-8d88-d39a1eb56a77.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create html and css for viewing a game's notes
- [x] Create click event on each game tile that will change the view to the notes
- [x] Create click event on the edit icon that will allow the user to edit the text of the notes
- [x] Create a html form for user to enter info.
- [x] Create css to style the form.
- [x] Create a submit event on the submit button.
- [x] Save user entered info to local storage.
- [x] Saved data is put onto the notes page.
- [x] Saved data is put into the input boxes on the edit page.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
