### ISSUE TITLE
Feature: User can delete a saved game

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

If a user wants to get rid of a saved game, they can delete it.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on a filled in heart in order to take it out of MyCodex and delete all notes associated with it.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue6mobile](https://user-images.githubusercontent.com/106547566/193701772-0d5daed8-e9ca-4ee8-9b11-c27d34b2f1c8.PNG)
![issue6desktop](https://user-images.githubusercontent.com/106547566/193701775-a5013311-4302-41ac-a687-7af60ce4f314.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a click event to filled in hearts
- [x] Show a confirmation modal when user clicks the filled in heart
- [x] Hide the modal if the user clicks cancel
- [x] Remove the entry from the data model and the entry's DOM tree from the page if the user clicks Confirm.
- [x] Change MyCodex display when empty.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that all previous functionality still works without errors.
