### ISSUE TITLE
Feature: User can create a new game entry

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/ajax-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a new game to their MyCodex page that they will be able to add and edit notes for.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the "Add a Game" button in order to bring up the form to fill in a name and image for the game they want to add. Once they submit this form, the game will be added to MyCodex and they can add and edit notes for it, just like any of the games from steam.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue7desktop](https://user-images.githubusercontent.com/106547566/193930046-4b346388-c2dd-49af-98b2-b4882366b99a.PNG)
![issue7mobile](https://user-images.githubusercontent.com/106547566/193930051-05d58294-1fa5-4932-8db9-acb94d0f82f9.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add buttons in MyCodex for adding a game and sorting
- [x] Add event listener to Add a Game button
- [x] Create HTML and CSS for Add a Game
- [x] Add a new view for addingGame
- [x] Add event listener to Submit button
- [x] Add title and image url to data.entries as a new entry
- [x] Add newly created game as a tile to MyCodex using dom creation
- [x] Add tile click event listener to new game tile
- [x] Clear the form
- [x] Return to MyCodex view after clicking submit
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
