### ISSUE TITLE
Feature: User can view a random steam game

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/ajax-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on the random button to see a random game on steam.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on the random icon in the nav bar, it will show the Random page with a random game from steam listed.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue8mobile](https://user-images.githubusercontent.com/106547566/194176763-16874108-23ad-4546-bd89-7877ad7eb43f.PNG)
![issue8desktop](https://user-images.githubusercontent.com/106547566/194176767-3c25ee91-b6cd-47ea-ad97-2fea0c8403df.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML and CSS for Random Event page
- [x] Create view for Random Event page
- [x] Add event listener on the random button
- [x] Generate a random number and save it to a variable
- [x] Use the generated random number to get app details using the API
- [x] Create the game tile using the dom
- [x] Make sure user can save the game
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
