### ISSUE TITLE
Feature: User can filter saved games

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/ajax-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can show only games of a particular play status.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the "Show" button and choose from one of the play statuses to show only games of that status.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue9mobile](https://user-images.githubusercontent.com/106547566/194651441-c6720463-b8df-4908-894f-ac22816adcd3.PNG)
![issue9desktop](https://user-images.githubusercontent.com/106547566/194651446-585219fa-1576-4335-8714-0bd1914d6343.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create status buttons that show on game tiles in MyCodex
- [x] Check for the value of the Show dropdown
- [x] Hide or show tiles based on their current play status
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
